version: "3.5"
services:

  db:
    image: "mongo:4.2-bionic"
    ports:
      - "27017:27017"

  api:
    build: ./api/
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/app
    ports:
      - "4000:4000"
    depends_on:
      - db

  web:
    build: ./web/
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/app
    ports:
      - "8080:8080"
    depends_on:
      - api
